using ClosedXML.Excel;
using CraftingPOS.Application.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CraftingPOS.Infrastructure.Reporting;

/// <summary>
/// Single exporter implementing both PDF (QuestPDF) and Excel (ClosedXML) output
/// for any tabular report, per SRS FR-REP-011.
/// </summary>
public class ReportExportService : IReportExportService
{
    static ReportExportService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public void ExportToPdf(string title, string subtitle, List<string> columnHeaders, List<List<string>> rows, string outputFilePath)
    {
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Column(col =>
                {
                    col.Item().Text(title).FontSize(18).Bold();
                    if (!string.IsNullOrWhiteSpace(subtitle))
                        col.Item().Text(subtitle).FontSize(11).FontColor(Colors.Grey.Darken1);
                    col.Item().PaddingTop(4).LineHorizontal(1);
                });

                page.Content().PaddingTop(10).Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        foreach (var _ in columnHeaders)
                            columns.RelativeColumn();
                    });

                    table.Header(header =>
                    {
                        foreach (var col in columnHeaders)
                        {
                            header.Cell().Background(Colors.Blue.Darken2).Padding(5)
                                .Text(col).FontColor(Colors.White).Bold();
                        }
                    });

                    foreach (var row in rows)
                    {
                        foreach (var cell in row)
                        {
                            table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).Padding(5).Text(cell);
                        }
                    }
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by CraftingPOS on ");
                    x.Span(DateTime.Now.ToString("dd MMM yyyy HH:mm"));
                });
            });
        }).GeneratePdf(outputFilePath);
    }

    public void ExportToExcel(string title, List<string> columnHeaders, List<List<string>> rows, string outputFilePath)
    {
        using var workbook = new XLWorkbook();
        var worksheet = workbook.Worksheets.Add(Truncate(title, 31)); // Excel sheet name limit

        for (var col = 0; col < columnHeaders.Count; col++)
        {
            var cell = worksheet.Cell(1, col + 1);
            cell.Value = columnHeaders[col];
            cell.Style.Font.Bold = true;
            cell.Style.Fill.BackgroundColor = XLColor.FromArgb(30, 58, 138);
            cell.Style.Font.FontColor = XLColor.White;
        }

        for (var r = 0; r < rows.Count; r++)
        {
            for (var c = 0; c < rows[r].Count; c++)
            {
                worksheet.Cell(r + 2, c + 1).Value = rows[r][c];
            }
        }

        worksheet.Columns().AdjustToContents();
        workbook.SaveAs(outputFilePath);
    }

    private static string Truncate(string text, int maxLength) =>
        text.Length <= maxLength ? text : text[..maxLength];
}